### ISSUE TITLE
Suggestion: split the project in 2

### ISSUE THREAD

**Issue by enricodias** [leproxy/leproxy#71]
I recently found  this project while searching for a simple pure php proxy for a project. I noticed that currently the project is focused on the end user with intention to build interfaces, launch browsers and so on. Wouldn't be better to split the project in 2?

The proxy itself could be a standalone composer package where anyone can use in their own projects. The user interface could be another project focused on ui/ux that just uses the proxy package.

**Comment by clue** [comment]
@enricodias Thanking for chiming in, I see your point. What do you think would be gained by splitting this into independent projects in its current state? It's my understanding all the issues discussed right now would be a reasonable feature additional to the current code base and it's unclear to me what's gained by splitting this into multiple repositories any time soon.

**Comment by enricodias** [comment]
Well, by splitting the project people like my that just want to use the proxy in their own project will be able to install the composer package while end users who just want to click and see it working could download the last release and execute it.

The 2 parts have very different requirements and purposes. While the proxy itself can be tested with unit tests, the UI requires more extensive tests such as integration tests in different platforms. I saw in other issue that you want even an windows executable version. Stuffing all those different things together doesn't seem to be the best idea for me and they break several rules from the unix principles (not that you _need_ to follow them).

Even the executable version may be splitted in different repositories since a windows .exe will be very different from a mac .dmg (or a brew bottle). There is no need to update the windows repository to fix a mac bug, for example. Those interfaces doesn't even need to use html, maybe a simple tray icon would do and they will have nothing in common with each other.

**Comment by clue** [comment]
I'm not sure I follow what problem you're seeing. This project can be used a proxy server standalone or in any other projects and this will not change with any of the proposed changes.

The suggested changes will add new features to the proxy server and will not change how it can be used or deployed. In particular, the Windows executable (#59) will most likely live outside of this project because it needs to bundle a PHP installation and more.

Regarding testing, all features will be covered by a sophisticated test suite, no matter how this project is split. This means tests have to be written regardless and splitting this project will only increase the maintenance overhead.

Anyway, thanks for sharing your thoughts, I think this is definitely something to keep in mind once the project advances. In it's current state, I don't think there's much to be done right now :+1:
