### ISSUE TITLE
Pass authentication to a FreeRADIUS server

### ISSUE THREAD

**Issue by metallicats** [leproxy/leproxy#77]
Is this possible?

**Comment by clue** [comment]
Absolutely possible!

RADIUS authentication is currently out of scope for the public roadmap because most end-users likely won't have a need for this. Instead, we're planning to release specific authentication mechanisms (SSO / single sign-on) as a commercial version as per #61.

If you're interested in commercial options or want to help sponsor this feature, feel free to reach out and send me an email.
